import 'package:equatable/equatable.dart'; import '../entities/knowledge_base.dart'; class GetKnowledgeBasesParams extends Equatable { final int page; final int limit; final KnowledgeBaseStatus? status; final KnowledgeBaseType? type; final String? search; final List<String>? tags; const GetKnowledgeBasesParams({this.page = 1, this.limit = 20, this.status, this.type, this.search, this.tags}); @override List<Object?> get props => [page, limit, status, type, search, tags]; }
class GetMyKnowledgeBasesParams extends Equatable { final int page; final int limit; final KnowledgeBaseStatus? status; final KnowledgeBaseType? type; const GetMyKnowledgeBasesParams({this.page = 1, this.limit = 20, this.status, this.type}); @override List<Object?> get props => [page, limit, status, type]; }
class GetKnowledgeBaseStatsParams extends Equatable { final String? userId; final DateTime? startDate; final DateTime? endDate; const GetKnowledgeBaseStatsParams({this.userId, this.startDate, this.endDate}); @override List<Object?> get props => [userId, startDate, endDate]; }
class ImportKnowledgeBaseParams extends Equatable { final String filePath; final String? name; final String? description; final KnowledgeBaseType type; const ImportKnowledgeBaseParams({required this.filePath, this.name, this.description, required this.type}); @override List<Object?> get props => [filePath, name, description, type]; }
class BatchDeleteKnowledgeBasesParams extends Equatable { final List<String> ids; const BatchDeleteKnowledgeBasesParams({required this.ids}); @override List<Object?> get props => [ids]; }
class GetPublicKnowledgeBasesParams extends Equatable { final int page; final int limit; final String? search; final List<String>? tags; const GetPublicKnowledgeBasesParams({this.page = 1, this.limit = 20, this.search, this.tags}); @override List<Object?> get props => [page, limit, search, tags]; }
class SearchKnowledgeBasesParams extends Equatable { final String query; final int page; final int limit; final KnowledgeBaseType? type; final List<String>? tags; const SearchKnowledgeBasesParams({required this.query, this.page = 1, this.limit = 20, this.type, this.tags}); @override List<Object?> get props => [query, page, limit, type, tags]; }
class UpdateKnowledgeBaseStatusParams extends Equatable { final String id; final KnowledgeBaseStatus status; const UpdateKnowledgeBaseStatusParams({required this.id, required this.status}); @override List<Object?> get props => [id, status]; }
class DuplicateKnowledgeBaseParams extends Equatable { final String id; final String? newName; const DuplicateKnowledgeBaseParams({required this.id, this.newName}); @override List<Object?> get props => [id, newName]; }
class ShareKnowledgeBaseParams extends Equatable { final String id; final List<String> userIds; final String? message; const ShareKnowledgeBaseParams({required this.id, required this.userIds, this.message}); @override List<Object?> get props => [id, userIds, message]; }
class ExportKnowledgeBaseParams extends Equatable { final String id; final String format; const ExportKnowledgeBaseParams({required this.id, required this.format}); @override List<Object?> get props => [id, format]; }
class BatchUpdateKnowledgeBaseStatusParams extends Equatable { final List<String> ids; final KnowledgeBaseStatus status; const BatchUpdateKnowledgeBaseStatusParams({required this.ids, required this.status}); @override List<Object?> get props => [ids, status]; }
